
package Control.GUI;

/**
 *
 * @author plhurtado y CCarcedo
 */

import javax.media.j3d.Canvas3D;
import Model.TheUniverse;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class ControlWindow extends JFrame {
  private TheUniverse universe;

  public ControlWindow(Canvas3D canvas, Canvas3D variable, TheUniverse anUniverse) {
    super();
    universe = anUniverse;
    initComponents();
    setLocation (1100, 500);
    addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent e) {
        cerrar(0);
      }
    });
    Visualization visualization = new Visualization (this, false, canvas, 1100, 0);
    visualization.setVisible(true);
    Visualization visualizationVariable = new Visualization (this, false, variable, 0, 0);
    visualizationVariable.setVisible(true);
    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primitiveGroup = new javax.swing.ButtonGroup();
        appearanceGroup = new javax.swing.ButtonGroup();
        perspectiva = new javax.swing.JButton();
        lunar = new javax.swing.JButton();
        CNave = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control");
        setMinimumSize(new java.awt.Dimension(300, 345));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        perspectiva.setText("Perspectiva");
        perspectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perspectivaActionPerformed(evt);
            }
        });
        getContentPane().add(perspectiva);

        lunar.setText("Camara Lunar");
        lunar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunarActionPerformed(evt);
            }
        });
        getContentPane().add(lunar);

        CNave.setText("Vista desde Nave");
        CNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNaveActionPerformed(evt);
            }
        });
        getContentPane().add(CNave);

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perspectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perspectivaActionPerformed
        universe.activarCamaraPerspectiva();
    }//GEN-LAST:event_perspectivaActionPerformed

    private void lunarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunarActionPerformed
        universe.activarCamaraLuna();
    }//GEN-LAST:event_lunarActionPerformed

    private void CNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNaveActionPerformed
        universe.activarCamaraNave();
    }//GEN-LAST:event_CNaveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        cerrar(0);
    }//GEN-LAST:event_ExitActionPerformed

  public void showWindow () {
    setVisible (true);
  }
  
  public void cerrar(int codigo){
      universe.salir(codigo);
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CNave;
    private javax.swing.JButton Exit;
    private javax.swing.ButtonGroup appearanceGroup;
    private javax.swing.JButton lunar;
    private javax.swing.JButton perspectiva;
    private javax.swing.ButtonGroup primitiveGroup;
    // End of variables declaration//GEN-END:variables
}
